### Say hello via HTTP
POST http://localhost:8080/v1/hello
{
    "name": "John Doe",
    "age": 55
}
{{
    test.status(200)
}}


### Say Hello via gRPC
GRPC grpc://localhost:50051/v1.HelloService/SayHello
{
    "name": "John Doe",
    "age": 55
}
{{
    test.status(0)
}}

### Say hello via gRPC with valid age
GRPC grpc://localhost:50051/v1.HelloService/SayHello
{
    "name": "John Doe",
    "age": 30
}
{{
    test.status(0)
}}

### Say hello via gRPC with invalid age
GRPC grpc://localhost:50051/v1.HelloService/SayHello
{
    "name": "John Doe",
    "age": -5
}
{{
    test.status(2)
}}

### Say hello via gRPC with invalid name
GRPC grpc://localhost:50051/v1.HelloService/SayHello
{
    "name": "",
    "age": 30
}
{{
    test.status(2)
}}

### Say hello via gRPC with no name
GRPC grpc://localhost:50051/v1.HelloService/SayHello
{
    "age": 30
}
{{
    test.status(2)
}}


### Greet many times via gRPC 
GRPC grpc://localhost:50051/v1.HelloService/GreetManyTimes
{
    "name": "John Doe"
}
{{
    test.status(0)
}}

### Long Greet via gRPC
GRPC grpc://localhost:50051/v1.HelloService/LongGreet
{
    "name": "John Doe"
}
{{@streaming
    async function writeStream() {
        await sleep(1000);
        await $requestClient.send({
            name : 'John Doe'
        });
        await sleep(1000);
        await $requestClient.send({
            name : 'Jane Doe'
        });
        await sleep(1000);
        await $requestClient.send({
            name : 'George Doe'
        });
    }
    exports.waitPromise = writeStream();
}}
{{
    test.status(0)
}}

