version: '3'

tasks:
  protogen:
    desc: Generate protobuf code
    cmds:
    - rm -rf protogen
    - rm -rf docs
    - buf dep update
    - buf generate
    - go mod tidy

    silent: true

  server:
    desc: Run the server
    cmds:
    - go run .
    - echo "Server is running..."
    silent: true

  lint:
    desc: Run linters
    cmds:
    - golangci-lint run ./...
    silent: true
